=== gitpan/Chess-PGN-Filter/pgn.dtd
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by Hugh S. Myers (private) -->
<!ELEMENT CHESSGAMES (GAME*)>
<!ATTLIST CHESSGAMES
	NAME CDATA #IMPLIED
>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT GAME (TAGLIST, GAMETEXT, POSITION*)>
<!ELEMENT TAGLIST (Event, Site, Date, Round, White, Black, Result, Annotator*, BlackElo*, BlackNA*, BlackTitle*, BlackType*, BlackUSCF*, Board*, ECO*, EventDate*, EventSponsor*, FEN*, Mode*, NIC*, Opening*, PlyCount*, Section*, SetUp*, Stage*, SubVariation*, Termination*, Time*, TimeControl*, UTCDate*, UTCTime*, Variation*, WhiteElo*, WhiteNA*, WhiteTitle*, WhiteType*, WhiteUSCF*)>
<!ELEMENT Event (#PCDATA)>
<!ELEMENT Site (#PCDATA)>
<!ELEMENT Date EMPTY>
<!ATTLIST Date
	YEAR CDATA #IMPLIED
	MONTH CDATA #IMPLIED
	DAY CDATA #IMPLIED
>
<!ELEMENT Round (#PCDATA)>
<!ELEMENT White (#PCDATA)>
<!ELEMENT Black (#PCDATA)>
<!ELEMENT Result EMPTY>
<!ATTLIST Result
	GAMERESULT (WHITEWIN | BLACKWIN | DRAW | UNKNOWN) #REQUIRED
>
<!ELEMENT Annotator (#PCDATA)>
<!ELEMENT BlackElo (#PCDATA)>
<!ELEMENT BlackNA (#PCDATA)>
<!ELEMENT BlackTitle (#PCDATA)>
<!ELEMENT BlackType (#PCDATA)>
<!ELEMENT BlackUSCF (#PCDATA)>
<!ELEMENT Board (#PCDATA)>
<!ELEMENT ECO (#PCDATA)>
<!ELEMENT EventDate (#PCDATA)>
<!ELEMENT EventSponsor (#PCDATA)>
<!ELEMENT FEN (#PCDATA)>
<!ELEMENT Mode (#PCDATA)>
<!ELEMENT NIC (#PCDATA)>
<!ELEMENT Opening (#PCDATA)>
<!ELEMENT PlyCount (#PCDATA)>
<!ELEMENT Section (#PCDATA)>
<!ELEMENT SetUp (#PCDATA)>
<!ELEMENT Stage (#PCDATA)>
<!ELEMENT SubVariation (#PCDATA)>
<!ELEMENT Termination (#PCDATA)>
<!ELEMENT Time (#PCDATA)>
<!ELEMENT TimeControl (#PCDATA)>
<!ELEMENT UTCDate (#PCDATA)>
<!ELEMENT UTCTime (#PCDATA)>
<!ELEMENT Variation (#PCDATA)>
<!ELEMENT WhiteElo (#PCDATA)>
<!ELEMENT WhiteNA (#PCDATA)>
<!ELEMENT WhiteTitle (#PCDATA)>
<!ELEMENT WhiteType (#PCDATA)>
<!ELEMENT WhiteUSCF (#PCDATA)>
<!ELEMENT GAMETEXT ((MOVENUMBER, (MOVE, (GAMETEXT*, COMMENT*, POSITION*, NAG*,FENstr*)*)*)+, GAMETERMINATION?)>
<!ELEMENT MOVENUMBER (#PCDATA)>
<!ELEMENT MOVE (#PCDATA)>
<!ELEMENT COMMENT (#PCDATA)>
<!ELEMENT POSITION (ROW+)>
<!ELEMENT ROW (#PCDATA)>
<!ATTLIST POSITION
	FONT CDATA #IMPLIED
	SIZE CDATA #IMPLIED
	xml:space (default | preserve) "preserve"
>
<!ELEMENT NAG (#PCDATA)>
<!ELEMENT FENstr (#PCDATA)>
<!ELEMENT GAMETERMINATION EMPTY>
<!ATTLIST GAMETERMINATION
	GAMERESULT (WHITEWIN | BLACKWIN | DRAW | UNKNOWN) #REQUIRED
>

=== gitpan/Chess-PGN-Filter/bcc95.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="pgn.xsl"?>
<!DOCTYPE CHESSGAMES SYSTEM "pgn.dtd">
<CHESSGAMES NAME="BCC95 Games">
		<GAME>
		<TAGLIST>
			<Event>Boise Chess Club Championship Reserve Section</Event>
			<Site>Boise (ID)</Site>
			<Date YEAR="1995" MONTH="02" DAY="28"/>
			<Round>01</Round>
			<White>Myers Hugh S (ID)</White>
			<Black>Roland Jeffrey T (ID)</Black>
			<Result GAMERESULT="BLACKWIN"/>
			<ECO>C00</ECO>
			<Opening>French: Labourdonnais variation</Opening>
		</TAGLIST>
		<GAMETEXT>
			<MOVENUMBER>1</MOVENUMBER>
			<MOVE>e4</MOVE>
			<FENstr>rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq -</FENstr>
			<MOVE>e6</MOVE>
			<FENstr>rnbqkbnr/pppp1ppp/4p3/8/4PP2/8/PPPP2PP/RNBQKBNR b KQkq f3</FENstr>
			<MOVENUMBER>2</MOVENUMBER>
			<MOVE>f4</MOVE>
			<FENstr>rnbqkbnr/pppp1ppp/4p3/8/4PP2/8/PPPP2PP/RNBQKBNR b KQkq f3</FENstr>
			<MOVE>d5</MOVE>
			<FENstr>rnbqkbnr/ppp2ppp/4p3/3p4/4PP2/8/PPPP2PP/RNBQKBNR w KQkq d6</FENstr>
			<MOVENUMBER>3</MOVENUMBER>
			<MOVE>e5</MOVE>
			<POSITION FONT="Chess Maya" SIZE="4">
				<ROW>1222222223</ROW>
				<ROW>4tMvWlVmT5</ROW>
				<ROW>4OoO +oOo5</ROW>
				<ROW>4 + +o+ +5</ROW>
				<ROW>4+ +oP + 5</ROW>
				<ROW>4 + + P +5</ROW>
				<ROW>4+ + + + 5</ROW>
				<ROW>4pPpP +pP5</ROW>
				<ROW>4RnBqKbNr5</ROW>
				<ROW>7888888889</ROW>
			</POSITION>
			<FENstr>rnbqkbnr/ppp2ppp/4p3/3p4/4PP2/8/PPPP2PP/RNBQKBNR w KQkq d6</FENstr>
			<MOVE>c5</MOVE>
			<FENstr>rnbqkbnr/ppp2ppp/4p3/3pP3/5P2/8/PPPP2PP/RNBQKBNR b KQkq -</FENstr>
			<MOVENUMBER>4</MOVENUMBER>
			<MOVE>Nf3</MOVE>
			<FENstr>rnbqkbnr/ppp2ppp/4p3/3pP3/5P2/8/PPPP2PP/RNBQKBNR b KQkq -</FENstr>
			<MOVE>Nc6</MOVE>
			<FENstr>rnbqkbnr/pp3ppp/4p3/2ppP3/5P2/8/PPPP2PP/RNBQKBNR w KQkq c6</FENstr>
			<MOVENUMBER>5</MOVENUMBER>
			<MOVE>d3</MOVE>
			<FENstr>rnbqkbnr/pp3ppp/4p3/2ppP3/5P2/8/PPPP2PP/RNBQKBNR w KQkq c6</FENstr>
			<MOVE>Be7</MOVE>
			<FENstr>rnbqkbnr/pp3ppp/4p3/2ppP3/5P2/5N2/PPPP2PP/RNBQKB1R b KQkq -</FENstr>
			<MOVENUMBER>6</MOVENUMBER>
			<MOVE>Be2</MOVE>
			<FENstr>rnbqkbnr/pp3ppp/4p3/2ppP3/5P2/5N2/PPPP2PP/RNBQKB1R b KQkq -</FENstr>
			<MOVE>Nh6</MOVE>
			<FENstr>r1bqkbnr/pp3ppp/2n1p3/2ppP3/5P2/5N2/PPPP2PP/RNBQKB1R w KQkq -</FENstr>
			<MOVENUMBER>7</MOVENUMBER>
			<MOVE>c3</MOVE>
			<FENstr>r1bqkbnr/pp3ppp/2n1p3/2ppP3/5P2/5N2/PPPP2PP/RNBQKB1R w KQkq -</FENstr>
			<MOVE>O-O</MOVE>
			<FENstr>r1bqkbnr/pp3ppp/2n1p3/2ppP3/5P2/3P1N2/PPP3PP/RNBQKB1R b KQkq -</FENstr>
			<MOVENUMBER>8</MOVENUMBER>
			<MOVE>O-O</MOVE>
			<FENstr>r1bqkbnr/pp3ppp/2n1p3/2ppP3/5P2/3P1N2/PPP3PP/RNBQKB1R b KQkq -</FENstr>
			<MOVE>f6</MOVE>
			<FENstr>r1bqk1nr/pp2bppp/2n1p3/2ppP3/5P2/3P1N2/PPP3PP/RNBQKB1R w KQkq -</FENstr>
			<MOVENUMBER>9</MOVENUMBER>
			<MOVE>exf6</MOVE>
			<FENstr>r1bqk1nr/pp2bppp/2n1p3/2ppP3/5P2/3P1N2/PPP3PP/RNBQKB1R w KQkq -</FENstr>
			<MOVE>Bxf6</MOVE>
			<FENstr>r1bqk1nr/pp2bppp/2n1p3/2ppP3/5P2/3P1N2/PPP1B1PP/RNBQK2R b KQkq -</FENstr>
			<MOVENUMBER>10</MOVENUMBER>
			<MOVE>d4</MOVE>
			<FENstr>r1bqk1nr/pp2bppp/2n1p3/2ppP3/5P2/3P1N2/PPP1B1PP/RNBQK2R b KQkq -</FENstr>
			<MOVE>cxd4</MOVE>
			<FENstr>r1bqk2r/pp2bppp/2n1p2n/2ppP3/5P2/3P1N2/PPP1B1PP/RNBQK2R w KQkq -</FENstr>
			<MOVENUMBER>11</MOVENUMBER>
			<MOVE>cxd4</MOVE>
			<FENstr>r1bqk2r/pp2bppp/2n1p2n/2ppP3/5P2/3P1N2/PPP1B1PP/RNBQK2R w KQkq -</FENstr>
			<MOVE>Qb6</MOVE>
			<FENstr>r1bqk2r/pp2bppp/2n1p2n/2ppP3/5P2/2PP1N2/PP2B1PP/RNBQK2R b KQkq -</FENstr>
			<MOVENUMBER>12</MOVENUMBER>
			<MOVE>Nc3</MOVE>
			<FENstr>r1bqk2r/pp2bppp/2n1p2n/2ppP3/5P2/2PP1N2/PP2B1PP/RNBQK2R b KQkq -</FENstr>
			<MOVE>Bxd4+</MOVE>
			<FENstr>r1bq1rk1/pp2bppp/2n1p2n/2ppP3/5P2/2PP1N2/PP2B1PP/RNBQK2R w KQ -</FENstr>
			<MOVENUMBER>13</MOVENUMBER>
			<MOVE>Kh1</MOVE>
			<FENstr>r1bq1rk1/pp2bppp/2n1p2n/2ppP3/5P2/2PP1N2/PP2B1PP/RNBQK2R w KQ -</FENstr>
			<MOVE>Bxc3</MOVE>
			<FENstr>r1bq1rk1/pp2bppp/2n1p2n/2ppP3/5P2/2PP1N2/PP2B1PP/RNBQ1RK1 b - -</FENstr>
			<MOVENUMBER>14</MOVENUMBER>
			<MOVE>bxc3</MOVE>
			<FENstr>r1bq1rk1/pp2bppp/2n1p2n/2ppP3/5P2/2PP1N2/PP2B1PP/RNBQ1RK1 b - -</FENstr>
			<MOVE>Ng4</MOVE>
			<FENstr>r1bq1rk1/pp2b1pp/2n1pp1n/2ppP3/5P2/2PP1N2/PP2B1PP/RNBQ1RK1 w - -</FENstr>
			<MOVENUMBER>15</MOVENUMBER>
			<MOVE>Nd4</MOVE>
			<FENstr>r1bq1rk1/pp2b1pp/2n1pp1n/2ppP3/5P2/2PP1N2/PP2B1PP/RNBQ1RK1 w - -</FENstr>
			<MOVE>Nxd4</MOVE>
			<FENstr>r1bq1rk1/pp2b1pp/2n1pP1n/2pp4/5P2/2PP1N2/PP2B1PP/RNBQ1RK1 b - -</FENstr>
			<MOVENUMBER>16</MOVENUMBER>
			<MOVE>cxd4</MOVE>
			<FENstr>r1bq1rk1/pp2b1pp/2n1pP1n/2pp4/5P2/2PP1N2/PP2B1PP/RNBQ1RK1 b - -</FENstr>
			<MOVE>Nf6</MOVE>
			<FENstr>r1bq1rk1/pp4pp/2n1pb1n/2pp4/5P2/2PP1N2/PP2B1PP/RNBQ1RK1 w - -</FENstr>
			<MOVENUMBER>17</MOVENUMBER>
			<MOVE>Ba3</MOVE>
			<FENstr>r1bq1rk1/pp4pp/2n1pb1n/2pp4/5P2/2PP1N2/PP2B1PP/RNBQ1RK1 w - -</FENstr>
			<MOVE>Rf7</MOVE>
			<FENstr>r1bq1rk1/pp4pp/2n1pb1n/2pp4/3P1P2/2P2N2/PP2B1PP/RNBQ1RK1 b - -</FENstr>
			<MOVENUMBER>18</MOVENUMBER>
			<MOVE>Rb1</MOVE>
			<FENstr>r1bq1rk1/pp4pp/2n1pb1n/2pp4/3P1P2/2P2N2/PP2B1PP/RNBQ1RK1 b - -</FENstr>
			<MOVE>Qd8</MOVE>
			<FENstr>r1bq1rk1/pp4pp/2n1pb1n/3p4/3p1P2/2P2N2/PP2B1PP/RNBQ1RK1 w - -</FENstr>
			<MOVENUMBER>19</MOVENUMBER>
			<MOVE>Bd3</MOVE>
			<FENstr>r1bq1rk1/pp4pp/2n1pb1n/3p4/3p1P2/2P2N2/PP2B1PP/RNBQ1RK1 w - -</FENstr>
			<MOVE>Bd7</MOVE>
			<FENstr>r1bq1rk1/pp4pp/2n1pb1n/3p4/3P1P2/5N2/PP2B1PP/RNBQ1RK1 b - -</FENstr>
			<MOVENUMBER>20</MOVENUMBER>
			<MOVE>Qf3</MOVE>
			<FENstr>r1bq1rk1/pp4pp/2n1pb1n/3p4/3P1P2/5N2/PP2B1PP/RNBQ1RK1 b - -</FENstr>
			<MOVE>Bc6</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1pb1n/3p4/3P1P2/5N2/PP2B1PP/RNBQ1RK1 w - -</FENstr>
			<MOVENUMBER>21</MOVENUMBER>
			<MOVE>f5</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1pb1n/3p4/3P1P2/5N2/PP2B1PP/RNBQ1RK1 w - -</FENstr>
			<MOVE>Ne4</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1pb1n/3p4/3P1P2/2N2N2/PP2B1PP/R1BQ1RK1 b - -</FENstr>
			<MOVENUMBER>22</MOVENUMBER>
			<MOVE>Bxe4</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1pb1n/3p4/3P1P2/2N2N2/PP2B1PP/R1BQ1RK1 b - -</FENstr>
			<MOVE>dxe4</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1p2n/3p4/3b1P2/2N2N2/PP2B1PP/R1BQ1RK1 w - -</FENstr>
			<MOVENUMBER>23</MOVENUMBER>
			<MOVE>Qd1</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1p2n/3p4/3b1P2/2N2N2/PP2B1PP/R1BQ1RK1 w - -</FENstr>
			<MOVE>exf5</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1p2n/3p4/3b1P2/2N2N2/PP2B1PP/R1BQ1R1K b - -</FENstr>
			<MOVENUMBER>24</MOVENUMBER>
			<MOVE>Rb2</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1p2n/3p4/3b1P2/2N2N2/PP2B1PP/R1BQ1R1K b - -</FENstr>
			<MOVE>Qd5</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1p2n/3p4/5P2/2b2N2/PP2B1PP/R1BQ1R1K w - -</FENstr>
			<MOVENUMBER>25</MOVENUMBER>
			<MOVE>Rbf2</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1p2n/3p4/5P2/2b2N2/PP2B1PP/R1BQ1R1K w - -</FENstr>
			<MOVE>e3</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1p2n/3p4/5P2/2P2N2/P3B1PP/R1BQ1R1K b - -</FENstr>
			<MOVENUMBER>26</MOVENUMBER>
			<MOVE>Re2</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1p2n/3p4/5P2/2P2N2/P3B1PP/R1BQ1R1K b - -</FENstr>
			<MOVE>Bb5</MOVE>
			<FENstr>r1b2rk1/pp4pp/1qn1p3/3p4/5Pn1/2P2N2/P3B1PP/R1BQ1R1K w - -</FENstr>
			<GAMETERMINATION GAMERESULT="BLACKWIN"/>
		</GAMETEXT>
	</GAME>
		<GAME>
		<TAGLIST>
			<Event>Boise Club Championship, Reserve Section</Event>
			<Site>Boise (ID)</Site>
			<Date YEAR="1995" MONTH="??" DAY="??"/>
			<Round>02</Round>
			<White>Mc Clory Charles</White>
			<Black>Myers Hugh S (ID)</Black>
			<Result GAMERESULT="DRAW"/>
			<ECO>A80</ECO>
			<Opening>Dutch</Opening>
		</TAGLIST>
		<GAMETEXT>
			<MOVENUMBER>1</MOVENUMBER>
			<MOVE>d4</MOVE>
			<FENstr>rnbqkbnr/ppppp1pp/8/5p2/3P4/8/PPP1PPPP/RNBQKBNR w KQkq f6</FENstr>
			<MOVE>f5</MOVE>
			<FENstr>rnbqkbnr/ppppp1pp/8/5p2/3P4/5N2/PPP1PPPP/RNBQKB1R b KQkq -</FENstr>
			<MOVENUMBER>2</MOVENUMBER>
			<MOVE>Nf3</MOVE>
			<FENstr>rnbqkbnr/ppppp1pp/8/5p2/3P4/5N2/PPP1PPPP/RNBQKB1R b KQkq -</FENstr>
			<MOVE>Nf6</MOVE>
			<FENstr>rnbqkb1r/ppppp1pp/5n2/5p2/3P4/5N2/PPP1PPPP/RNBQKB1R w KQkq -</FENstr>
			<MOVENUMBER>3</MOVENUMBER>
			<MOVE>e3</MOVE>
			<FENstr>rnbqkb1r/ppppp1pp/5n2/5p2/3P4/5N2/PPP1PPPP/RNBQKB1R w KQkq -</FENstr>
			<MOVE>e6</MOVE>
			<FENstr>rnbqkb1r/ppppp1pp/5n2/5p2/3P4/4PN2/PPP2PPP/RNBQKB1R b KQkq -</FENstr>
			<MOVENUMBER>4</MOVENUMBER>
			<MOVE>Be2</MOVE>
			<FENstr>rnbqkb1r/ppppp1pp/5n2/5p2/3P4/4PN2/PPP2PPP/RNBQKB1R b KQkq -</FENstr>
			<MOVE>Be7</MOVE>
			<FENstr>rnbqkb1r/pppp2pp/4pn2/5p2/3P4/4PN2/PPP2PPP/RNBQKB1R w KQkq -</FENstr>
			<MOVENUMBER>5</MOVENUMBER>
			<MOVE>c4</MOVE>
			<FENstr>rnbqkb1r/pppp2pp/4pn2/5p2/3P4/4PN2/PPP2PPP/RNBQKB1R w KQkq -</FENstr>
			<MOVE>d6</MOVE>
			<FENstr>rnbqkb1r/pppp2pp/4pn2/5p2/3P4/4PN2/PPP1BPPP/RNBQK2R b KQkq -</FENstr>
			<MOVENUMBER>6</MOVENUMBER>
			<MOVE>O-O</MOVE>
			<FENstr>rnbqkb1r/pppp2pp/4pn2/5p2/3P4/4PN2/PPP1BPPP/RNBQK2R b KQkq -</FENstr>
			<MOVE>c6</MOVE>
			<FENstr>rnbqk2r/ppppb1pp/4pn2/5p2/3P4/4PN2/PPP1BPPP/RNBQK2R w KQkq -</FENstr>
			<MOVENUMBER>7</MOVENUMBER>
			<MOVE>Nc3</MOVE>
			<FENstr>rnbqk2r/ppppb1pp/4pn2/5p2/3P4/4PN2/PPP1BPPP/RNBQK2R w KQkq -</FENstr>
			<MOVE>O-O</MOVE>
			<FENstr>rnbqk2r/ppppb1pp/4pn2/5p2/2PP4/4PN2/PP2BPPP/RNBQK2R b KQkq c3</FENstr>
			<MOVENUMBER>8</MOVENUMBER>
			<MOVE>Bd3</MOVE>
			<FENstr>rnbqk2r/ppppb1pp/4pn2/5p2/2PP4/4PN2/PP2BPPP/RNBQK2R b KQkq c3</FENstr>
			<MOVE>d5</MOVE>
			<FENstr>rnbqk2r/ppp1b1pp/3ppn2/5p2/2PP4/4PN2/PP2BPPP/RNBQK2R w KQkq -</FENstr>
			<MOVENUMBER>9</MOVENUMBER>
			<MOVE>b3</MOVE>
			<FENstr>rnbqk2r/ppp1b1pp/3ppn2/5p2/2PP4/4PN2/PP2BPPP/RNBQK2R w KQkq -</FENstr>
			<MOVE>h6</MOVE>
			<FENstr>rnbqk2r/ppp1b1pp/3ppn2/5p2/2PP4/4PN2/PP2BPPP/RNBQ1RK1 b kq -</FENstr>
			<MOVENUMBER>10</MOVENUMBER>
			<MOVE>h3</MOVE>
			<FENstr>rnbqk2r/ppp1b1pp/3ppn2/5p2/2PP4/4PN2/PP2BPPP/RNBQ1RK1 b kq -</FENstr>
			<MOVE>Bd7</MOVE>
			<FENstr>rnbqk2r/pp2b1pp/2pppn2/5p2/2PP4/4PN2/PP2BPPP/RNBQ1RK1 w kq -</FENstr>
			<MOVENUMBER>11</MOVENUMBER>
			<MOVE>c5</MOVE>
